In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [8]:
x = torch.linspace(-5, 5, 10)
x

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])

In [9]:
sigmoid = torch.sigmoid(x)
sigmoid

tensor([0.0067, 0.0201, 0.0585, 0.1589, 0.3646, 0.6354, 0.8411, 0.9415, 0.9799,
        0.9933])

In [10]:
tanh = torch.tanh(x)
tanh

tensor([-0.9999, -0.9992, -0.9923, -0.9311, -0.5047,  0.5047,  0.9311,  0.9923,
         0.9992,  0.9999])

In [11]:
relu = F.relu(x)
relu

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5556, 1.6667, 2.7778, 3.8889,
        5.0000])

In [16]:
alpha: float = 0.1
leakyRelu = F.leaky_relu(x, negative_slope = alpha)
leakyRelu

tensor([-0.5000, -0.3889, -0.2778, -0.1667, -0.0556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])