In [1]:
import torch

In [2]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
w = torch.tensor([1.5, -0.5], requires_grad=True)
b = torch.tensor([1.0], requires_grad=True)

In [6]:
activation = x @ w + b
activation

tensor([2.5000], grad_fn=<AddBackward0>)

In [7]:
output = torch.sigmoid(activation)
output

tensor([0.9241], grad_fn=<SigmoidBackward0>)

In [8]:
target = torch.tensor([1.0])
target

tensor([1.])

In [9]:
loss = (output - target) ** 2
loss

tensor([0.0058], grad_fn=<PowBackward0>)

In [10]:
loss.backward()

In [11]:
x.grad

tensor([-0.0160,  0.0053])

In [12]:
w.grad

tensor([-0.0213, -0.0319])

In [13]:
b.grad

tensor([-0.0106])